[package]
name = "pf_ndk_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pf_ndk_glue={path="../pf_ndk_glue"}


[lib]
crate-type=["cdylib"]

[[example]]
name="hello"
crate-type=["cdylib"]
